name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "reopened"]
    branches: ["main"]

permissions:
  contents: read

env: 
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk:
    permissions:
      contents: read           # for actions/checkout to fetch code
      security-events: write   # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read            # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Snyk
        uses: snyk/actions/python-3.10@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
